export default {
  type: "object",
  properties: {
    trainer_id: { type: "string" },
    student_id: { type: "string" },
    trainingType: { type: "string" },
    duration: { type: "string" },
    specialization: { type: "string" },
    trainingName: { type: "string" },
    startDate: { type: "string" },
    endDate: { type: "string" },
    trainerName: { type: "string" },
    studentName: { type: "string" },
    description: { type: "string" },
  },
  required: [
    "trainer_id",
    "student_id",
    "trainingType",
    "duration",
    "specialization",
    "trainingName",
    "startDate",
    "endDate",
    "trainerName",
    "studentName",
  ],
} as const;
